### ISSUE TITLE
Compilation Error : Hello class does not have required constructor

### ISSUE THREAD

**Issue by anshulkatta** [alek-sys/spring-functional-microframework#1]
public Hello(String name){
    	this.name=  name;
    }

Above constructor must be added to resolve the compilation error.

**Comment by alek-sys** [comment]
Make sure you have Lombok plugin installed and annotation processor enabled for your project. For more details please refer to https://projectlombok.org/

**Comment by alek-sys** [comment]
Pleas refer to branch [no-lombok](https://github.com/alek-sys/spring-functional-microframework/tree/no-lombok) for details
